apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: pipeline
  name: pipeline
  namespace: default
spec:
  selector:
    matchLabels:
      app: pipeline
  template:
    metadata:
      labels:
        app: pipeline
    spec:
      containers:
      - image: gcr.io/kubernetes-ml-dev/pipeline:3c038050b9103b93ece99b3373498dd353b28923
        name: pipeline
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
